config/routes.rb
Rails.application.routes.draw do
  root to: "groups#index"
  resources :groups do
    resources :employees, only: [ :new, :create, :destroy]
    resources :team


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :description, presence: true
  belongs_to :group
  belongs_to :team
  validates :group_id, uniqueness: { scope: :team_id }
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :employees, dependent: :destroy
  has_many :teams, through: :employees
  mount_uploader :photo, PhotoUploader
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
   @employee = Employee.new
   @group = Group.find(params[:group_id])
   @teams = Team.all

  end

  def create

    @employee = Employee.new(employees_params)
    @group = Group.find(params[:group_id])
    @employee.group = @group
     if @employee.save
      redirect_to group_path(@group)
    else
      render :new
    end

  end

  def destroy
    @employee = Employee.find(params[:id])
    @group = Group.find(params[:group_id])
    @employee.destroy
    redirect_to group_path(@group)
  end

  private

  def employees_params
    params.require(:employee).permit(:description, :team_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_path(@group)
    else
      render :new
    end

  end

  private

  def group_params
    params.require(:group).permit(:name, :body, :photo)
  end
end

app/controllers/teams_controller.rb
class TeamController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/new.html.erb
<div class="wrapper">
<div class="container">
  <div class="text-center">
<div class="title-photo">
<h1>Groups <%= @group.name %></h1>
<%= cl_image_tag( @group.photo , :cloud_name => @group.name,
      width: 400, height: 300, crop: :fill, class: "img-rad", style: "background: linear-gradient(purple, black);") %>
  </div>

<h1>Add your employees</h1>
<%= simple_form_for [@group, @employee] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence, class: "error alert alert-danger" if f.object.errors[:base].present? %>
<div class="form-inputs">
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="desc">
      <%= f.input :description %>
      </div>
    </div>
    </div>
    <div class="col-md-6 col-sm-12">
      <div class="ing">
        <%= f.association :team %>
      </div>
    </div>
    <div class="col-md-12 col-sm-12">
      <div>
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>
</div>

app/views/employees/show.html.erb
<h1>Employees#show</h1>
<p>Find me in app/views/employees/show.html.erb</p>

app/views/groups/_form.html.erb
<div class="wrapper">
<div class="container">
  <div class="text-center">
    <div class="form-container">
    <div class="c-title">
      <h1>Create your own group</h1>
    </div>
    <%= simple_form_for(@group) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?%>
      <div class="c-name">
        <%= f.input :name %>
      </div>
      <div class="c-submit">
        <%= f.button :submit, class: 'btn btn-primary'%>
      </div>
    <% end %>
    </div>
  </div>
</div>
</div>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/index.html.erb
<%= render "shared/banner" %>
  <div class="container">
    <div class="row">
        <% @groups.each do |c| %>
           <%= link_to group_path(c) do %>
          <div class="col-xs-12 col-sm-6 col-md-3">
           <div class="card card-link"
           style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url(https://media-exp1.licdn.com/dms/image/C560BAQEFI1_beVvTkQ/company-logo_200_200/0?e=1611792000&v=beta&t=OMML-nqVpisyaiQw6q1qSJ8_nUIObhTiPtBql19PdFc)">
            <div class="card-description">
              <h2><%= c.name %></h2>
            </div>

          </div>
        </div>
        <% end %>
        <% end %>
    </div>
</div>

app/views/groups/new.html.erb
<div class="wrapper">
  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="text-center">
      <div class="title-photo">
        <h1 style="color: black;"><%= @group.name %></h1>

        <div class="card card-link card-show img-rad"
        style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
        url(https://media-exp1.licdn.com/dms/image/C560BAQEFI1_beVvTkQ/company-logo_200_200/0?e=1611792000&v=beta&t=OMML-nqVpisyaiQw6q1qSJ8_nUIObhTiPtBql19PdFc)">
        </div>
      </div>
      <br>

      <div class="employees-t">
       <table>
        <div class="thead">
          <tr>
            <th>
              <h4>
                Team
              </h4>
            </th>
            <th>
              <h4>
                Employee
              </h4>
            </th>
          </tr>
        </div>
        <tbody class="t-body">
        <% @group.employees.each do |employee| %>
        <div class="tdetails">
          <tr>
            <td>
              <h5> <%= employee.team.name %></h5>
            </td>
            <td>
              <h5>
               <%= employee.description %> <%= link_to group_employee_path(@group, employee),
               method: :delete,
               data: { confirm: "Are you sure?" }, class: 'link' do%>
               <i class="fas fa-trash-alt delete-employee"></i>
               <% end %>
             </h5>
           </td>
           <% end %>
         </tr>
       </div>
        </tbody>
     </table>
   </div>
   <hr>
   <%= link_to "Add employees to your group", new_group_employee_path(@group), class: 'btn btn-success' %>
   <hr>
   <%= link_to "Back to the list", groups_path, class: 'link2' %>
 </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Data Guard Group</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'shared/navbar' %>
<%= yield %>
  <%= render 'shared/footer' %>
<%= javascript_include_tag "application" %>
<%= javascript_pack_tag "application" %>
</div>

</body>
</html>

app/views/shared/_banner.html.erb
 <div>
 <div>
   <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://media-exp1.licdn.com/dms/image/C4D1BAQEQElL9CMzkwg/company-background_10000/0?e=1603724400&v=beta&t=CY3U36mSsVa-SLDTQksLnWjyE1WzK8Of9atxSPXEeHQ');">
    <div class="banner-content">
      <h1>Data Guard Groups Generator</h1>
      <p>
        <span id="banner-typed-text"></span>
      </p>
      <div>
       <button type="button" class="btn btn-info" data-toggle="modal" data-target=".bs-example-modal-sm">How to use?</button>

       <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabell">
        <div class="modal-dialog modal-sm" role="document">
          <div class="modal-content font">
            <ol>
              <li>
                Click New Group
              </li>
              <li>
                Add the employees of your group
              </li>
              <li>
                You have your group on the website
              </li>
              <li>
                Click on "Choose Group" to see which group will go out next
              </li>
               <h5 class="font" style="font-weight: bolder;">Press the Logo on the top to go back to the home page</h3>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'New Group',new_group_path, class: 'btn btn-success' %>
    <%= link_to 'Choose Group', group_path(@groups.shuffle.first), class: 'btn btn-primary' %>
  </div>
</div>
</div>
</div>

app/views/shared/_card.html.erb
  <div class="container">
    <div class="row">
        <% @groups.each do |c| %>
           <%= link_to group_path(c) do %>
          <div class="col-xs-12 col-sm-6 col-md-3">
           <div class="card card-link"
           style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url(<%= c.photo %>)">
            <div class="card-description">
              <h2><%= c.name %></h2>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
    </div>
</div>

app/views/shared/_footer.html.erb
<div>
  <div class="footer">
    <div class="footer-links">
      <a href="https://github.com/ashrafuthman"><i class="fab fa-github"></i></a>
      <a href="https://www.facebook.com/ashraf.uthman.9"><i class="fab fa-facebook-f"></i></i></a>
      <a href="https://www.linkedin.com/in/ashraf-uthman-47b56715a/"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This website is made with <i class="fa fa-heart"></i>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container">
  <div class="text-center">

    <h1>Create your own group</h1>

    <%= simple_form_for(@group) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>




        <%= f.input :name %>
        <%= f.input :photo, label: false %>
        <%= f.input :photo_cache, as: :hidden%>



        <%= f.button :submit, class: 'btn btn-primary'%>

      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/shared/_modal.html.erb
<div>
 <button type="button" class="btn btn-primary fas fa-info" data-toggle="modal" data-target=".bs-example-modal-sm">How to use?</button>
 <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabell">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content font">
      <ol>
        <li>
          Click New Group
        </li>
        <li>
          Name your group and upload picture of your group
        </li>
        <li>
          Add the employees of your group
        </li>
        <li>
          You have your group on the website
        </li>
         <h5 class="font" style="font-weight: bolder;">Press the Logo on the top to go back to the home page</h3>
      </ol>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="text-center">
    <%= link_to (image_tag "DataG.jpeg", class: 'logo'), groups_path %>
  </div>
</div>